language: r
sudo: required

before_install:
  - curl -OL https://raw.githubusercontent.com/psolaimani/BenchmarkR/master/travis-tool.sh
  - chmod 755 ./travis-tool.sh

install:
  - ./travis-tool.sh install_github jimhester/covr
  - ./travis-tool.sh install_github bedatadriven/hamcrest
  - ./travis-tool.sh install_r pacman
  - ./travis-tool.sh install_deps

env:
 global:
   - CRAN: http://cran.rstudio.com
   - R_BUILD_ARGS=--no-manual
   - R_CHECK_ARGS=--no-manual --as-cran
   - R_CHECK_FORCE_SUGGESTS_=FALSE
   
# Support codecov
r_github_packages:
  - psolaimani/benchmarkR

after_success:
  - Rscript -e 'library(covr);codecov()'
