language: r
sudo: required
# Used to extract name of packages used in scripts
#r_binary_packages:
# - stringr

env:
 global:
   - CRAN: http://cran.rstudio.com
   - WARNINGS_ARE_ERRORS=1
   - R_BUILD_ARGS=--no-manual
   - R_CHECK_ARGS=--no-manual --as-cran
   
# Support codecov
r_github_packages:
  - jimhester/covr
  - psolaimani/BiocInstaller
#  - hadley/stringr
  - psolaimani/benchmarkR

after_success:
  - Rscript -e 'library(covr);codecov()'
