language: r
sudo: required
# Used to extract name of packages used in scripts
#r_binary_packages:
# - stringr

# Support codecov
r_github_packages:
  - jimhester/covr
  - Bioconductor-mirror/BiocInstaller
#  - hadley/stringr
  - psolaimani/benchmarkR

after_success:
  - Rscript -e 'library(covr);codecov()'
