language: r
sudo: required

env:
 global:
   - CRAN: http://cran.rstudio.com
   - R_BUILD_ARGS=--no-manual
   - R_CHECK_ARGS=--no-manual --as-cran
   
# Support codecov
r_github_packages:
  - jimhester/covr
  - psolaimani/benchmarkR

after_success:
  - Rscript -e 'library(covr);codecov()'
